version: '3.4'
services:
  geth.dnp.dappnode.eth:
    image: 'geth.dnp.dappnode.eth:0.1.1'
    build: ./build
    volumes:
      - 'geth:/root/.ethereum'
    environment:
      - EXTRA_OPTS=
    ports:
      - '127.0.0.1:8546:8546'
      - '127.0.0.1:8545:8545'
      - '61313:30303'
      - '61313:30303/udp'
      - '61314:30304/udp'
volumes:
  geth: {}
