version: '3.4'
services:
  idchain.dnp.dappnode.eth:
    image: 'idchain.dnp.dappnode.eth:0.0.1'
    build: ./build
    volumes:
      - 'idchain:/idchain'
    environment:
      - 'EXTRA_OPTS=--rpcapi eth,net,web3,txpool'
      - SYNCMODE=fast
    ports:
      - '30329:30329'
      - '30329:30329/udp'
    restart: always
volumes:
  idchain: {}
